# Additional services for complete monitoring stack
# Use with: docker-compose -f docker-compose.yml -f docker-compose.monitoring.yml up -d
services:
  # Redis metrics exporter
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: gmail-cleaner-redis-exporter
    restart: unless-stopped
    environment:
      REDIS_ADDR: "redis:6379"
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - gmail-cleaner-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  # Node exporter for system metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: gmail-cleaner-node-exporter
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
    networks:
      - gmail-cleaner-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  # Alertmanager for handling alerts
  alertmanager:
    image: prom/alertmanager:latest
    container_name: gmail-cleaner-alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - gmail-cleaner-network
    profiles:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  # Loki for log aggregation (optional)
  loki:
    image: grafana/loki:latest
    container_name: gmail-cleaner-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki.yml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - gmail-cleaner-network
    profiles:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Promtail for shipping logs to Loki
  promtail:
    image: grafana/promtail:latest
    container_name: gmail-cleaner-promtail
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/gmail-cleaner:ro
      - ./monitoring/promtail.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - gmail-cleaner-network
    profiles:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  # Update Prometheus to include alert rules
  prometheus:
    volumes:
      - ./monitoring/alerts:/etc/prometheus/alerts:ro

volumes:
  alertmanager-data:
    driver: local
  loki-data:
    driver: local
