# Alertmanager configuration for Gmail Cleaner
global:
  resolve_timeout: 5m
  
  # SMTP configuration for email alerts (optional)
  # smtp_smarthost: 'smtp.gmail.com:587'
  # smtp_from: 'alertmanager@example.com'
  # smtp_auth_username: 'alertmanager@example.com'
  # smtp_auth_password: 'your-app-password'
  # smtp_require_tls: true

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree for alerts
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  
  routes:
    # Critical alerts
    - match:
        severity: critical
      receiver: 'critical'
      continue: true
    
    # Warning alerts
    - match:
        severity: warning
      receiver: 'warning'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h

# Receivers
receivers:
  - name: 'default'
    # Add your notification config here
    
  - name: 'critical'
    # Email notifications for critical alerts
    # email_configs:
    #   - to: 'admin@example.com'
    #     headers:
    #       Subject: 'CRITICAL: Gmail Cleaner Alert'
    
    # Slack notifications (optional)
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    #     channel: '#alerts'
    #     title: 'Gmail Cleaner Critical Alert'
    
    # PagerDuty (optional)
    # pagerduty_configs:
    #   - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
    
  - name: 'warning'
    # Email notifications for warnings
    # email_configs:
    #   - to: 'admin@example.com'
    #     headers:
    #       Subject: 'WARNING: Gmail Cleaner Alert'
    #     send_resolved: true

# Inhibition rules
inhibit_rules:
  # If the whole app is down, don't send other alerts
  - source_match:
      alertname: 'GmailAPIDown'
    target_match_re:
      alertname: '.*'
    equal: ['service']
  
  # If Redis is down, don't alert on cache issues
  - source_match:
      alertname: 'RedisDown'
    target_match:
      alertname: 'LowCacheHitRate'
    equal: ['service']
