global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'gmail-cleaner'
    environment: 'production'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Gmail Cleaner App metrics
  - job_name: 'gmail-cleaner-app'
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Redis metrics (using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node exporter for system metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Gmail Cleaner specific metrics to track:
# - gmail_emails_processed_total
# - gmail_emails_deleted_total
# - gmail_api_requests_total
# - gmail_api_errors_total
# - gmail_cache_hits_total
# - gmail_cache_misses_total
# - gmail_operation_duration_seconds
# - gmail_active_sessions
# - gmail_cleanup_rules_executed_total
# - gmail_cleanup_rules_failed_total
